routes/web.php
<?php
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/manage-booking', 'GeneralController@manageBooking');
    Route::get('/search-booking', 'GeneralController@searchBooking');
    Route::post('/search/ticket', 'GeneralController@searchTicket' );
    Route::get('/metrics','GeneralController@metrics');
    Route::get('misc/tops','GeneralController@topMisc');
    Route::get('misc/refunds','GeneralController@showRefunds');
    Route::get('misc/cancelled-tickets','GeneralController@showCancelledTickets');
    Route::resource('misc/feedback','FeedbackController');
    Route::get('/insights','GeneralController@insights');
    Route::resource('/issues-report', 'ReportController');
    Route::get('/home', 'HomeController@index')->name('home');

    //settings
    Route::group(['prefix' => 'settings'], function (){
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController');
        Route::resource('issues', 'IssueController');
    });
//tickets
    Route::group(['prefix' => 'tickets'], function (){
        Route::get('show/{id}','TicketController@show');
    });
//reports
    Route::group(['prefix' => 'reports'], function (){
        Route::get('customers', 'ReportController@customers');
        Route::get('download-excel', 'ReportController@downloadExcel');
    });
//users actions
    Route::group(['prefix' => 'actions'], function (){
        Route::get('cancel-ticket/{id}', 'ActionController@cancelTicket');
        Route::get('re-send-sms/{id}', 'ActionController@resendSms');
        Route::get('refund/{id}', 'ActionController@refund');
        Route::get('re-book/{id}', 'ActionController@reBook');
        Route::get('confirm-refund/{id}', 'ActionController@confirmRefund');
        Route::get('feedback/{id}', 'ActionController@feedback');
        Route::get('confirm-payment/{id}', 'ActionController@confirmPayment');
        Route::post('cancel-ticket/save', 'ActionController@cancelTicketSave');
        Route::post('send-sms/save', 'ActionController@smsSave');
        Route::post('refund/save', 'ActionController@refundSave');
        Route::post('refund/confirm', 'ActionController@refundCustomer');
        Route::post('feedback/save', 'ActionController@feedbacksave');
        Route::post('confirm-payment/save', 'ActionController@confirmPaymentSave');
    });

});

Route::get('clear-cache/{command}','RoleController@clearCache');

Auth::routes();

resources/views/issue-report/create.blade.php
@extends('layouts.main')

@section('css')

@endsection
@section('content')

    <div class="page-content-wrapper">
        <div class="page-content">

            @component('components.breadcump')

                @slot('title')
                    Issue
                @endslot

                @slot('span')
                    add issue
                @endslot
                    issues
                @slot('menu')
                    <div class="page-toolbar">
                        <div class="btn-group pull-right">
                            <a href="{{ url()->previous() }}" class="btn btn-fit-height grey-salt" > Back
                                {{--<i class="fa fa-angle-down"></i>--}}
                            </a>
                        </div>
                    </div>
                @endslot

            @endcomponent

            <div class="search-page search-content-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light ">
                            <div class="portlet-title">
                                <div class="caption font-dark">
                                    <span class="caption-subject bold uppercase">Add Issue</span>
                                </div>
                                <div class="tools"> </div>
                            </div>
                            <form action="{{ route('issues-report.store') }}" method="post">
                                {{ csrf_field() }}

                                <div class="portlet-body">
                                    <div class="row">
                                        <div class="form-group col-sm-6">
                                            <label for="ticket_on">Ticket NO</label>
                                            <input name="ticket_on" id="ticket_on" onkeyup="searchTicket()" value="{{ old('ticket_on')  }}" required type="text" class="form-control">
                                            <div id="display"></div>
                                            @if ($errors->has('ticket_on'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('ticket_on') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group col-sm-6">
                                            <label for="description">Description</label>
                                            <input name="description" id="description" value="{{ old('description') }}" type="text" class="form-control">
                                            @if($errors->has('description'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('description') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group col-sm-6  pull-right">
                                            <br>
                                            <button type="submit" class="btn pull-right btn-primary">Add</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>

@endsection

@section('scripts')

@endsection

resources/views/issue-report/edit.blade.php
@extends('layouts.main')

@section('css')

@endsection
@section('content')

    <div class="page-content-wrapper">
        <div class="page-content">

            @component('components.breadcump')

                @slot('title')
                    Issue Types
                @endslot

                @slot('span')
                    edit issue type
                @endslot

                    issue types
                @slot('menu')
                        <div class="page-toolbar">
                            <div class="btn-group pull-right">
                                <a href="{{ url()->previous() }}" class="btn btn-fit-height grey-salt" > Back
                                    {{--<i class="fa fa-angle-down"></i>--}}
                                </a>
                            </div>
                        </div>
                @endslot

            @endcomponent

            <div class="search-page search-content-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light ">
                            <div class="portlet-title">
                                <div class="caption font-dark">
                                    <span class="caption-subject bold uppercase">Edit Issue Type</span>
                                </div>
                                <div class="tools"> </div>
                            </div>
                            <form action="{{ route('issues.update', $issue->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('put') }}

                                <div class="portlet-body">
                                    <div class="row">
                                        <div class="form-group col-sm-6">
                                            <label for="role">Issue Type</label>
                                            <input name="role" id="role" value="{{ ucwords($issue->issue)  }}" required type="text" class="form-control">
                                            @if ($errors->has('role'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('role') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group col-sm-6">
                                            <label for="description">Description</label>
                                            <input name="description" id="description" value="{{ $issue->description }}" type="text" class="form-control">
                                            @if($errors->has('description'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('description') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group col-sm-6  pull-right">
                                            <br>
                                            <button type="submit" class="btn pull-right btn-primary">Edit</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

@section('scripts')

@endsection

resources/views/issue-report/index.blade.php
@extends('layouts.main')

@section('css')

@endsection
@section('content')

    <div class="page-content-wrapper">
        <div class="page-content">

            @component('components.breadcump')

                @slot('title')
                    Issue Types
                @endslot

                @slot('span')
                    manage issue type
                @endslot

                issue types

                @slot('menu')
                        <div class="page-toolbar">
                            <div class="btn-group pull-right">
                                <a href="{{ route('issues.create') }}" class="btn btn-fit-height grey-salt" > Add Issue
                                    {{--<i class="fa fa-angle-down"></i>--}}
                                </a>
                            </div>
                        </div>
                @endslot

            @endcomponent

            <div class="search-page search-content-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light ">
                            <div class="portlet-title">
                                <div class="caption font-dark">
                                    <span class="caption-subject bold uppercase">Issue Types</span>
                                </div>
                                <div class="tools"> </div>
                            </div>
                            <div class="portlet-body">
                                <table class="table table-striped table-bordered table-hover dt-responsive" width="100%">
                                    <thead>
                                    <tr>
                                        <th >NO:</th>
                                        <th >Issue Type</th>
                                        <th >Description</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($issues as $issue)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ ucwords($issue->issue) }}</td>
                                            <td>{{ ucfirst($issue->description) }}</td>
                                            <td class="text-center">
                                                <form action="{{ route('issues.destroy', $issue->id) }}" method="post">
                                                    {{ csrf_field() }}
                                                    {{ method_field('delete') }}
                                                    <a href="{{ route('issues.edit', $issue->id) }}" class="btn green">
                                                        <i class="fa fa-pencil"></i></a>

                                                    <button class="btn red"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

@section('scripts')

@endsection