routes/web.php
<?php
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/manage-booking', 'GeneralController@manageBooking');
    Route::get('/search-booking', 'GeneralController@searchBooking');
    Route::post('/search/ticket', 'GeneralController@searchTicket' );
    Route::get('/metrics','GeneralController@metrics');
    Route::get('misc/tops','GeneralController@topMisc');
    Route::get('misc/refunds','GeneralController@showRefunds');
    Route::get('misc/cancelled-tickets','GeneralController@showCancelledTickets');
    Route::resource('misc/feedback','FeedbackController');
    Route::get('/insights','GeneralController@insights');
    Route::resource('/issues-report', 'ReportController');
    Route::get('/home', 'HomeController@index')->name('home');

    //settings
    Route::group(['prefix' => 'settings'], function (){
        Route::resource('users', 'UserController');
        Route::resource('roles', 'RoleController');
        Route::resource('issues', 'IssueController');
    });
//tickets
    Route::group(['prefix' => 'tickets'], function (){
        Route::get('show/{id}','TicketController@show');
    });
//reports
    Route::group(['prefix' => 'reports'], function (){
        Route::get('customers', 'ReportController@customers');
        Route::get('download-excel', 'ReportController@downloadExcel');
    });
//users actions
    Route::group(['prefix' => 'actions'], function (){
        Route::get('cancel-ticket/{id}', 'ActionController@cancelTicket');
        Route::get('re-send-sms/{id}', 'ActionController@resendSms');
        Route::get('refund/{id}', 'ActionController@refund');
        Route::get('re-book/{id}', 'ActionController@reBook');
        Route::get('confirm-refund/{id}', 'ActionController@confirmRefund');
        Route::get('feedback/{id}', 'ActionController@feedback');
        Route::get('confirm-payment/{id}', 'ActionController@confirmPayment');
        Route::post('cancel-ticket/save', 'ActionController@cancelTicketSave');
        Route::post('send-sms/save', 'ActionController@smsSave');
        Route::post('refund/save', 'ActionController@refundSave');
        Route::post('refund/confirm', 'ActionController@refundCustomer');
        Route::post('feedback/save', 'ActionController@feedbacksave');
        Route::post('confirm-payment/save', 'ActionController@confirmPaymentSave');
    });

});

Route::get('clear-cache/{command}','RoleController@clearCache');

Auth::routes();

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\Handler;
use Illuminate\Http\Request;
use Riazxrazor\LaravelSweetAlert\LaravelSweetAlert;
use Sgr\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('settings.roles.index')
            ->withRoles(Role::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('settings.roles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Role::create($request->all());
        LaravelSweetAlert::setMessageSuccess("successful");
        return redirect('/settings/roles');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('settings.roles.edit')
            ->withRole($role);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $role->update($request->all());
        LaravelSweetAlert::setMessageSuccess("successful");
        return redirect('settings/roles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->users()->delete();
        $role->delete();
        LaravelSweetAlert::setMessageSuccess("successful");
        return redirect('settings/roles');
    }

    public function clearCache($request)
    {
        Handler::clearCache($request);
    }
}

resources/views/settings/roles/create.blade.php
@extends('layouts.main')

@section('css')

@endsection
@section('content')

    <div class="page-content-wrapper">
        <div class="page-content">

            @component('components.breadcump')

                @slot('title')
                    Roles
                @endslot

                @slot('span')
                    add role
                @endslot
                    roles
                @slot('menu')
                    <div class="page-toolbar">
                        <div class="btn-group pull-right">
                            <a href="{{ url()->previous() }}" class="btn btn-fit-height grey-salt" > Back
                                {{--<i class="fa fa-angle-down"></i>--}}
                            </a>
                        </div>
                    </div>
                @endslot

            @endcomponent

            <div class="search-page search-content-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light ">
                            <div class="portlet-title">
                                <div class="caption font-dark">
                                    <span class="caption-subject bold uppercase">Add Role</span>
                                </div>
                                <div class="tools"> </div>
                            </div>
                            <form action="{{ route('roles.store') }}" method="post">
                                {{ csrf_field() }}

                                <div class="portlet-body">
                                    <div class="row">
                                        <div class="form-group col-sm-6">
                                            <label for="role">Roles</label>
                                            <input name="role" id="role" value="{{ old('role')  }}" required type="text" class="form-control">
                                            @if ($errors->has('role'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('role') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group col-sm-6">
                                            <label for="description">Description</label>
                                            <input name="description" id="description" value="{{ old('description') }}" type="text" class="form-control">
                                            @if($errors->has('description'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('description') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group col-sm-6  pull-right">
                                            <br>
                                            <button type="submit" class="btn pull-right btn-primary">Add Role</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>

@endsection

@section('scripts')

@endsection

resources/views/settings/roles/edit.blade.php
@extends('layouts.main')

@section('css')

@endsection
@section('content')

    <div class="page-content-wrapper">
        <div class="page-content">

            @component('components.breadcump')

                @slot('title')
                    Roles
                @endslot

                @slot('span')
                    edit role
                @endslot

                roles
                @slot('menu')
                        <div class="page-toolbar">
                            <div class="btn-group pull-right">
                                <a href="{{ url()->previous() }}" class="btn btn-fit-height grey-salt" > Back
                                    {{--<i class="fa fa-angle-down"></i>--}}
                                </a>
                            </div>
                        </div>
                @endslot

            @endcomponent

            <div class="search-page search-content-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light ">
                            <div class="portlet-title">
                                <div class="caption font-dark">
                                    <span class="caption-subject bold uppercase">Edit Role</span>
                                </div>
                                <div class="tools"> </div>
                            </div>
                            <form action="{{ route('roles.update', $role->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('put') }}

                                <div class="portlet-body">
                                    <div class="row">
                                        <div class="form-group col-sm-6">
                                            <label for="role">Role</label>
                                            <input name="role" id="role" value="{{ ucwords($role->role)  }}" required type="text" class="form-control">
                                            @if ($errors->has('role'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('role') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group col-sm-6">
                                            <label for="description">Description</label>
                                            <input name="description" id="description" value="{{ $role->description }}" type="text" class="form-control">
                                            @if($errors->has('description'))
                                                <span class="help-block">
                                                    <strong>{{ $errors->first('description') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group col-sm-6  pull-right">
                                            <br>
                                            <button type="submit" class="btn pull-right btn-primary">Edit Role</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

@section('scripts')

@endsection

resources/views/settings/roles/index.blade.php
@extends('layouts.main')

@section('css')

@endsection
@section('content')

    <div class="page-content-wrapper">
        <div class="page-content">

            @component('components.breadcump')

                @slot('title')
                    Roles
                @endslot

                @slot('span')
                    manage roles
                @endslot

                roles

                @slot('menu')
                        <div class="page-toolbar">
                            <div class="btn-group pull-right">
                                <a href="{{ route('roles.create') }}" class="btn btn-fit-height green" > Add Role
                                    {{--<i class="fa fa-angle-down"></i>--}}
                                </a>
                            </div>
                        </div>
                @endslot

            @endcomponent

            <div class="search-page search-content-1">
                <div class="row">
                    <div class="col-md-12">
                        <div class="portlet light ">
                            <div class="portlet-title">
                                <div class="caption font-dark">
                                    <span class="caption-subject bold uppercase">Roles</span>
                                </div>
                                <div class="tools"> </div>
                            </div>
                            <div class="portlet-body">
                                <table class="table table-striped table-bordered table-hover dt-responsive" width="100%">
                                    <thead>
                                    <tr>
                                        <th >NO:</th>
                                        <th >Role</th>
                                        <th >Description</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($roles as $role)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ ucwords($role->role) }}</td>
                                            <td>{{ ucfirst($role->description) }}</td>
                                            <td class="text-center">
                                                @if($role->id !=1)
                                                <form action="{{ route('roles.destroy', $role->id) }}" method="post">
                                                    {{ csrf_field() }}
                                                    {{ method_field('delete') }}
                                                    <a href="{{ route('roles.edit', $role->id) }}" class="btn green">
                                                        <i class="fa fa-pencil"></i></a>

                                                    <button class="btn red"><i class="fa fa-trash"></i></button>
                                                </form>
                                                    @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

@section('scripts')

@endsection